### ISSUE TITLE
(Sentry test) TypeError: Object [object Object] has no method 'updateFrom'

### ISSUE THREAD

**Issue by reinout** [nens/waterlabel-client#34]
https://sentry.io/nens/waterlabelnet-frontend/issues/293299031/

```
TypeError: Object [object Object] has no method 'updateFrom'
  at poll (../../sentry/scripts/views.js:389:46)
  at merge (../../sentry/scripts/views.js:268:16)
  at member (../../sentry/scripts/views.js:283:50)

This is an example javascript exception
```

**Comment by reinout** [comment]
Test geslaagd
